export interface Facility {
  name: string;
  address: string;
}

export const facilities: Facility[] = [
  { name: "Montgomery Processing Center", address: "806 Hilbig Road, Conroe, TX 77301" },
  { name: "Houston Contract Detention Facility", address: "15850 Export Plaza Drive, Houston, TX 77032" },
  { name: "Joe Corley Detention Facility", address: "500 Hilbig Road, Conroe, TX 77301" },
  { name: "IAH Secure Adult Detention Facility", address: "3400 Highway 146, Livingston, TX 77351" },
  { name: "South Texas ICE Processing Center", address: "566 Veterans Drive, Pearsall, TX 78061" },
  { name: "Port Isabel Service Processing Center", address: "27991 Buena Vista Boulevard, Los Fresnos, TX 78566" },
  { name: "Rio Grande Detention Center", address: "1001 Loop 20, Laredo, TX 78043" },
  { name: "Laredo Processing Center", address: "4702 East Saunders, Laredo, TX 78041" },
  { name: "El Valle Detention Facility", address: "1005 West Hidalgo Avenue, Raymondville, TX 78580" },
  { name: "South Texas Family Residential Center", address: "300 El Rancho Way, Dilley, TX 78017" },
  { name: "Karnes County Residential Center", address: "409 FM 1144, Karnes City, TX 78118" },
  { name: "T. Don Hutto Residential Center", address: "1001 Welch Street, Taylor, TX 76574" },
  { name: "West Texas Detention Facility", address: "1700 West IH-10, Sierra Blanca, TX 79851" },
  { name: "El Paso Service Processing Center", address: "8915 Montana Avenue, El Paso, TX 79925" },
  { name: "Bluebonnet Detention Center", address: "300 Avenue F, Anson, TX 79501" },
  { name: "Prairieland Detention Facility", address: "1209 Sunflower Lane, Alvarado, TX 76009" },
  { name: "Limestone County Detention Center", address: "1100 East Milam Street, Groesbeck, TX 76642" },
  { name: "LaSalle ICE Processing Center", address: "830 Pine Hill Road, Jena, LA 71342" },
  { name: "Pine Prairie ICE Processing Center", address: "1133 Hampton Dupre Road, Pine Prairie, LA 70576" },
  { name: "Winn Correctional Center", address: "1318 Winnfield Bypass, Winnfield, LA 71483" },
  { name: "Allen Parish Public Safety Complex", address: "7340 Highway 26, Oberlin, LA 70655" },
  { name: "Richwood Correctional Center", address: "180 Old Richwood Road, Monroe, LA 71202" },
  { name: "South Louisiana ICE Processing Center", address: "3843 Stagg Avenue, Basile, LA 70515" },
  { name: "River Correctional Center", address: "968 Highway 568, Ferriday, LA 71334" },
  { name: "Central Louisiana ICE Processing Center", address: "830 Pine Hill Road, Jena, LA 71342" },
  { name: "Eloy Detention Center", address: "1705 East Hanna Road, Eloy, AZ 85131" },
  { name: "La Palma Correctional Center", address: "5501 North La Palma Road, Eloy, AZ 85131" },
  { name: "Florence Service Processing Center", address: "3250 North Pinal Parkway, Florence, AZ 85132" },
  { name: "Central Arizona Florence Correctional Complex", address: "1100 Bowling Road, Florence, AZ 85132" },
  { name: "Adelanto ICE Processing Center", address: "10250 Rancho Road, Adelanto, CA 92301" },
  { name: "Otay Mesa Detention Center", address: "7488 Calzada de la Fuente, San Diego, CA 92154" },
  { name: "Imperial Regional Detention Facility", address: "1572 Gateway Road, Calexico, CA 92231" },
  { name: "Mesa Verde ICE Processing Center", address: "425 Golden State Avenue, Bakersfield, CA 93301" },
  { name: "Golden State Annex", address: "611 Frontage Road, McFarland, CA 93250" },
  { name: "Yuba County Jail", address: "215 5th Street, Marysville, CA 95901" },
  { name: "Stewart Detention Center", address: "146 CCA Road, Lumpkin, GA 31815" },
  { name: "Folkston ICE Processing Center", address: "3026 Scrubby Bluff Road, Folkston, GA 31537" },
  { name: "Irwin County Detention Center", address: "132 Cotton Drive, Ocilla, GA 31774" },
  { name: "Otero County Processing Center", address: "26 McGregor Range Road, Chaparral, NM 88081" },
  { name: "Cibola County Correctional Center", address: "2000 Cibola Loop, Milan, NM 87021" },
  { name: "Torrance County Detention Facility", address: "209 County Road A013, Estancia, NM 87016" },
  { name: "Krome North Service Processing Center", address: "18201 SW 12th Street, Miami, FL 33194" },
  { name: "Broward Transitional Center", address: "3900 North Powerline Road, Pompano Beach, FL 33073" },
  { name: "Glades County Detention Center", address: "1297 East SR 78, Moore Haven, FL 33471" },
  { name: "Baker County Detention Center", address: "1 Sheriffs Office Drive, Macclenny, FL 32063" },
  { name: "Wakulla County Jail", address: "15 Oak Street, Crawfordville, FL 32327" },
  { name: "Northwest ICE Processing Center", address: "1623 East J Street, Tacoma, WA 98421" },
  { name: "Moshannon Valley Processing Center", address: "555 Geo Drive, Philipsburg, PA 16866" },
  { name: "Clinton County Correctional Facility", address: "58 Pine Mountain Road, McElhattan, PA 17748" },
  { name: "Pike County Correctional Facility", address: "175 Pike County Boulevard, Lords Valley, PA 18428" },
  { name: "York County Prison", address: "3400 Concord Road, York, PA 17402" },
  { name: "Buffalo Federal Detention Facility", address: "4250 Federal Drive, Batavia, NY 14020" },
  { name: "Orange County Correctional Facility", address: "110 Wells Farm Road, Goshen, NY 10924" },
  { name: "Elizabeth Contract Detention Facility", address: "625 Evans Street, Elizabeth, NJ 07201" },
  { name: "Bergen County Jail", address: "160 South River Street, Hackensack, NJ 07601" },
  { name: "Essex County Correctional Facility", address: "354 Doremus Avenue, Newark, NJ 07105" },
  { name: "Hudson County Correctional Facility", address: "30-35 Hackensack Avenue, Kearny, NJ 07032" },
  { name: "Plymouth County Correctional Facility", address: "26 Long Pond Road, Plymouth, MA 02360" },
  { name: "Strafford County Department of Corrections", address: "266 County Farm Road, Dover, NH 03820" },
  { name: "Bristol County House of Correction", address: "400 Faunce Corner Road, North Dartmouth, MA 02747" },
  { name: "Suffolk County House of Correction", address: "20 Bradston Street, Boston, MA 02118" },
  { name: "Etowah County Detention Center", address: "827 Forrest Avenue, Gadsden, AL 35901" },
  { name: "Caroline Detention Facility", address: "11093 Lewis B Puller Memorial Highway, Bowling Green, VA 22427" },
  { name: "Farmville Detention Center", address: "508 Waterworks Road, Farmville, VA 23901" },
  { name: "Worcester County Detention Center", address: "5022 Joyner Road, Snow Hill, MD 21863" },
  { name: "Howard County Detention Center", address: "7301 Waterloo Road, Jessup, MD 20794" },
  { name: "Boone County Jail", address: "3020 Conrad Lane, Burlington, KY 41005" },
  { name: "Clay County Detention Center", address: "609 East Jackson Street, Brazil, IN 47834" },
  { name: "Pulaski County Detention Center", address: "1058 New Era Road, Ullin, IL 62992" },
  { name: "Kenosha County Detention Center", address: "4777 88th Avenue, Kenosha, WI 53144" },
  { name: "Dodge Detention Facility", address: "216 West Center Street, Juneau, WI 53039" },
  { name: "McHenry County Adult Correctional Facility", address: "2200 North Seminary Avenue, Woodstock, IL 60098" },
  { name: "Calhoun County Correctional Facility", address: "185 East Michigan Avenue, Battle Creek, MI 49014" },
  { name: "Chippewa County Correctional Facility", address: "4498 West M-80, Sault Ste Marie, MI 49783" },
  { name: "Monroe County Dorm", address: "7000 East Dunbar Road, Monroe, MI 48161" },
  { name: "Geauga County Safety Center", address: "12450 Merritt Road, Chardon, OH 44024" },
  { name: "Morrow County Correctional Facility", address: "101 Home Road, Mount Gilead, OH 43338" },
  { name: "Seneca County Jail", address: "3040 South State Route 100, Tiffin, OH 44883" },
  { name: "Butler County Jail", address: "705 Hanover Street, Hamilton, OH 45011" },
  { name: "Tri-County Detention Center", address: "1026 Shawnee College Road, Ullin, IL 62992" },
  { name: "Polk County Jail", address: "1985 NE 51st Place, Des Moines, IA 50313" },
  { name: "Carver County Jail", address: "606 East 4th Street, Chaska, MN 55318" },
  { name: "Freeborn County Adult Detention Center", address: "411 South Broadway Avenue, Albert Lea, MN 56007" },
  { name: "Kandiyohi County Jail", address: "2201 NE 23rd Street, Willmar, MN 56201" },
  { name: "Sherburne County Jail", address: "13880 Business Center Drive NW, Elk River, MN 55330" },
  { name: "Hardin County Jail", address: "1116 14th Avenue, Eldora, IA 50627" },
  { name: "Linn County Correctional Center", address: "53 3rd Avenue Bridge, Cedar Rapids, IA 52401" },
  { name: "Saline County Jail", address: "251 North 10th Street, Salina, KS 67401" },
  { name: "Chase County Detention Facility", address: "201 East 11th Street, Imperial, NE 69033" },
  { name: "Phelps County Jail", address: "1115 Burlington Street, Holdrege, NE 68949" },
  { name: "Hall County Department of Corrections", address: "121 South Pine Street, Grand Island, NE 68801" },
  { name: "Henry County Justice Center", address: "123 East Washington Street, Mount Pleasant, IA 52641" },
  { name: "Aurora ICE Processing Center", address: "3130 North Oakland Street, Aurora, CO 80010" },
  { name: "Teller County Detention Facility", address: "288 West Highway 24, Cripple Creek, CO 80813" },
  { name: "Garfield County Jail", address: "107 8th Street, Glenwood Springs, CO 81601" },
  { name: "Park County Detention Center", address: "1131 11th Street, Cody, WY 82414" },
  { name: "Cache County Jail", address: "1225 West Valley View Avenue, Logan, UT 84321" },
  { name: "Davis County Jail", address: "800 West State Street, Farmington, UT 84025" },
  { name: "Weber County Correctional Facility", address: "1400 Depot Drive, Ogden, UT 84404" },
  { name: "Henderson Detention Center", address: "18 East Basic Road, Henderson, NV 89015" },
  { name: "Nye County Detention Center", address: "1520 East Basin Avenue, Pahrump, NV 89060" },
  { name: "Northern Oregon Regional Correctional Facility", address: "201 Webber Street, The Dalles, OR 97058" },
  { name: "Yakima County Department of Corrections", address: "111 North Front Street, Yakima, WA 98901" },
  { name: "Honolulu Federal Detention Center", address: "351 Elliott Street, Honolulu, HI 96819" },
  { name: "Anchorage Correctional Complex", address: "1400 East 4th Avenue, Anchorage, AK 99501" },
  { name: "Alexandria Staging Facility", address: "830 Pine Hill Road, Alexandria, LA 71303" },
  { name: "Desert View Annex", address: "10400 Rancho Road, Adelanto, CA 92301" },
];

const facilityMap = new Map(facilities.map((f) => [f.name, f.address]));

export function getFacilityAddress(name: string): string | undefined {
  return facilityMap.get(name);
}
