export interface ImmigrationCourt {
  name: string;
  address: string;
  courtType: string;
}

export const immigrationCourts: ImmigrationCourt[] = [
  { name: "Houston Immigration Court", address: "600 Jefferson Street, Suite 800, Houston, TX 77002", courtType: "Non-detained" },
  { name: "Houston - Greenspoint Park Immigration Court", address: "16800 Greenspoint Park Drive, Suite 400-S, Houston, TX 77060", courtType: "Non-detained" },
  { name: "Houston Service Processing Center Immigration Court", address: "15850 Export Plaza Drive, Houston, TX 77032", courtType: "Detained" },
  { name: "Conroe Immigration Court", address: "806 Hilbig Road, Conroe, TX 77301", courtType: "Detained" },
  { name: "Montgomery Immigration Court", address: "806 Hilbig Road, Conroe, TX 77301", courtType: "Detained" },
  { name: "San Antonio Immigration Court", address: "800 Dolorosa Street, Suite 300, San Antonio, TX 78207", courtType: "Non-detained" },
  { name: "Pearsall Immigration Court", address: "566 Veterans Drive, Pearsall, TX 78061", courtType: "Detained" },
  { name: "Port Isabel Immigration Court", address: "27991 Buena Vista Boulevard, Los Fresnos, TX 78566", courtType: "Detained" },
  { name: "Harlingen Immigration Court", address: "2009 West Jefferson Street, Suite 300, Harlingen, TX 78550", courtType: "Non-detained" },
  { name: "Laredo Immigration Court", address: "1300 Matamoros Street, Laredo, TX 78040", courtType: "Mixed" },
  { name: "Dilley Immigration Court", address: "300 El Rancho Way, Dilley, TX 78017", courtType: "Detained (Family)" },
  { name: "Karnes Immigration Court", address: "409 FM 1144, Karnes City, TX 78118", courtType: "Detained (Family)" },
  { name: "El Paso Immigration Court", address: "700 East San Antonio Avenue, Suite B-410, El Paso, TX 79901", courtType: "Mixed" },
  { name: "El Paso Service Processing Center Immigration Court", address: "8915 Montana Avenue, El Paso, TX 79925", courtType: "Detained" },
  { name: "Dallas Immigration Court", address: "1100 Commerce Street, Suite 404, Dallas, TX 75242", courtType: "Non-detained" },
  { name: "Fort Worth Immigration Adjudication Center", address: "819 Taylor Street, Room 8A24, Fort Worth, TX 76102", courtType: "Adjudication Center" },
  { name: "Prairieland Immigration Court", address: "1209 Sunflower Lane, Alvarado, TX 76009", courtType: "Detained" },
  { name: "Atlanta Immigration Court", address: "180 Spring Street SW, Suite 241, Atlanta, GA 30303", courtType: "Non-detained" },
  { name: "Stewart Immigration Court", address: "146 CCA Road, Lumpkin, GA 31815", courtType: "Detained" },
  { name: "Folkston Immigration Court", address: "3026 Scrubby Bluff Road, Folkston, GA 31537", courtType: "Detained" },
  { name: "Miami Immigration Court", address: "333 South Miami Avenue, Suite 700, Miami, FL 33130", courtType: "Non-detained" },
  { name: "Miami Krome Immigration Court", address: "18201 SW 12th Street, Miami, FL 33194", courtType: "Detained" },
  { name: "Orlando Immigration Court", address: "3535 Lawton Road, Suite 200, Orlando, FL 32803", courtType: "Non-detained" },
  { name: "Bradenton Immigration Court", address: "1521 Manatee Avenue West, Bradenton, FL 34205", courtType: "Non-detained" },
  { name: "Pompano Beach Immigration Court", address: "3900 North Powerline Road, Pompano Beach, FL 33073", courtType: "Detained" },
  { name: "New Orleans Immigration Court", address: "1250 Poydras Street, Suite 800, New Orleans, LA 70113", courtType: "Non-detained" },
  { name: "Oakdale Immigration Court", address: "1900 East Whatley Road, Oakdale, LA 71463", courtType: "Detained" },
  { name: "Jena Immigration Court", address: "830 Pine Hill Road, Jena, LA 71342", courtType: "Detained" },
  { name: "Pine Prairie Immigration Court", address: "1133 Hampton Dupre Road, Pine Prairie, LA 70576", courtType: "Detained" },
  { name: "Phoenix Immigration Court", address: "2035 North Central Avenue, Phoenix, AZ 85004", courtType: "Non-detained" },
  { name: "Eloy Immigration Court", address: "1705 East Hanna Road, Eloy, AZ 85131", courtType: "Detained" },
  { name: "Florence Immigration Court", address: "3260 North Pinal Parkway, Florence, AZ 85132", courtType: "Detained" },
  { name: "Tucson Immigration Court", address: "300 West Congress Street, Suite 200, Tucson, AZ 85701", courtType: "Mixed" },
  { name: "Los Angeles Immigration Court (Olive Street)", address: "606 South Olive Street, 15th Floor, Los Angeles, CA 90014", courtType: "Non-detained" },
  { name: "Los Angeles Immigration Court (Van Nuys)", address: "15400 Sherman Way, Suite 300, Van Nuys, CA 91406", courtType: "Non-detained" },
  { name: "Los Angeles Immigration Court (North Los Angeles Street)", address: "300 North Los Angeles Street, Room 5400, Los Angeles, CA 90012", courtType: "Non-detained" },
  { name: "Los Angeles Immigration Court (West LA)", address: "11500 West Olympic Boulevard, Suite 600, Los Angeles, CA 90064", courtType: "Non-detained" },
  { name: "Adelanto Immigration Court", address: "10250 Rancho Road, Adelanto, CA 92301", courtType: "Detained" },
  { name: "San Diego Immigration Court", address: "401 West A Street, Suite 800, San Diego, CA 92101", courtType: "Mixed" },
  { name: "Otay Mesa Immigration Court", address: "7488 Calzada de la Fuente, San Diego, CA 92154", courtType: "Detained" },
  { name: "Imperial Immigration Court", address: "1572 Gateway Road, Calexico, CA 92231", courtType: "Detained" },
  { name: "San Francisco Immigration Court", address: "100 Montgomery Street, Suite 800, San Francisco, CA 94104", courtType: "Non-detained" },
  { name: "Sacramento Immigration Court", address: "650 Capitol Mall, Suite 1-200, Sacramento, CA 95814", courtType: "Non-detained" },
  { name: "Mesa Verde Immigration Court", address: "425 Golden State Avenue, Bakersfield, CA 93301", courtType: "Detained" },
  { name: "San Pedro Immigration Court", address: "2001 South Palos Verdes Street, San Pedro, CA 90731", courtType: "Detained" },
  { name: "New York City Immigration Court (Federal Plaza)", address: "26 Federal Plaza, 12th Floor, New York, NY 10278", courtType: "Non-detained" },
  { name: "New York City Immigration Court (Broadway)", address: "290 Broadway, Suite 1100, New York, NY 10007", courtType: "Non-detained" },
  { name: "New York City Immigration Court (Varick Street)", address: "201 Varick Street, Room 1140, New York, NY 10014", courtType: "Detained" },
  { name: "Buffalo Immigration Court", address: "130 Delaware Avenue, Suite 200, Buffalo, NY 14202", courtType: "Non-detained" },
  { name: "Batavia Immigration Court", address: "4250 Federal Drive, Batavia, NY 14020", courtType: "Detained" },
  { name: "Ulster Immigration Court", address: "750 Berme Road, Napanoch, NY 12458", courtType: "Detained" },
  { name: "Newark Immigration Court", address: "970 Broad Street, Suite 1200, Newark, NJ 07102", courtType: "Non-detained" },
  { name: "Elizabeth Immigration Court", address: "625 Evans Street, Elizabeth, NJ 07201", courtType: "Detained" },
  { name: "Boston Immigration Court", address: "5 Post Office Square, 8th Floor, Boston, MA 02109", courtType: "Non-detained" },
  { name: "Hartford Immigration Court", address: "450 Main Street, 4th Floor, Hartford, CT 06103", courtType: "Non-detained" },
  { name: "Philadelphia Immigration Court", address: "900 Market Street, Suite 500, Philadelphia, PA 19107", courtType: "Non-detained" },
  { name: "Moshannon Valley Immigration Court", address: "555 Geo Drive, Philipsburg, PA 16866", courtType: "Detained" },
  { name: "York Immigration Court", address: "3400 Concord Road, York, PA 17402", courtType: "Detained" },
  { name: "Baltimore Immigration Court", address: "31 Hopkins Plaza, Suite 1600, Baltimore, MD 21201", courtType: "Non-detained" },
  { name: "Hyattsville Immigration Court", address: "6525 Belcrest Road, Suite 200, Hyattsville, MD 20782", courtType: "Non-detained" },
  { name: "Arlington Immigration Court", address: "1901 South Bell Street, Suite 200, Arlington, VA 22202", courtType: "Non-detained" },
  { name: "Sterling Immigration Court", address: "22685 Holiday Park Drive, Suite 240, Sterling, VA 20166", courtType: "Non-detained" },
  { name: "Annandale Immigration Court", address: "7411 Boston Boulevard, Springfield, VA 22153", courtType: "Non-detained" },
  { name: "Richmond Immigration Court", address: "1010 East Main Street, Suite 600, Richmond, VA 23219", courtType: "Non-detained" },
  { name: "Falls Church Immigration Adjudication Center", address: "5107 Leesburg Pike, Falls Church, VA 22041", courtType: "Adjudication Center" },
  { name: "Caroline Immigration Court", address: "11093 Lewis B Puller Memorial Highway, Bowling Green, VA 22427", courtType: "Detained" },
  { name: "Farmville Immigration Court", address: "508 Waterworks Road, Farmville, VA 23901", courtType: "Detained" },
  { name: "Charlotte Immigration Court", address: "5701 Executive Center Drive, Suite 300, Charlotte, NC 28212", courtType: "Non-detained" },
  { name: "Memphis Immigration Court", address: "167 North Main Street, Suite 1100, Memphis, TN 38103", courtType: "Mixed" },
  { name: "Chicago Immigration Court", address: "525 West Van Buren Street, Suite 500, Chicago, IL 60607", courtType: "Non-detained" },
  { name: "Broadview Immigration Court", address: "1930 Beach Street, Broadview, IL 60155", courtType: "Detained" },
  { name: "Detroit Immigration Court", address: "333 Mt. Elliott Street, Suite 200, Detroit, MI 48207", courtType: "Non-detained" },
  { name: "Cleveland Immigration Court", address: "1240 East 9th Street, Room 585, Cleveland, OH 44199", courtType: "Non-detained" },
  { name: "Kansas City Immigration Court", address: "2345 Grand Boulevard, Suite 600, Kansas City, MO 64108", courtType: "Non-detained" },
  { name: "St. Louis Immigration Court", address: "1222 Spruce Street, Room 1.107, St. Louis, MO 63103", courtType: "Non-detained" },
  { name: "Omaha Immigration Court", address: "1717 Avenue H, Suite 100, Omaha, NE 68110", courtType: "Non-detained" },
  { name: "Bloomington Immigration Court", address: "1 Federal Drive, Suite 1850, Fort Snelling, MN 55111", courtType: "Non-detained" },
  { name: "Fort Snelling Immigration Court", address: "1 Federal Drive, Suite 1850, Fort Snelling, MN 55111", courtType: "Non-detained" },
  { name: "Salt Lake City Immigration Court", address: "2975 South Decker Lake Drive, Suite 100, West Valley City, UT 84119", courtType: "Non-detained" },
  { name: "Denver Immigration Court", address: "1961 Stout Street, Suite 1200, Denver, CO 80294", courtType: "Non-detained" },
  { name: "Aurora Immigration Court", address: "3130 North Oakland Street, Aurora, CO 80010", courtType: "Detained" },
  { name: "Las Vegas Immigration Court", address: "3373 Pepper Lane, Suite 200, Las Vegas, NV 89120", courtType: "Non-detained" },
  { name: "Portland Immigration Court", address: "1220 SW 3rd Avenue, Room 902, Portland, OR 97204", courtType: "Non-detained" },
  { name: "Seattle Immigration Court", address: "1000 Second Avenue, Suite 2500, Seattle, WA 98104", courtType: "Non-detained" },
  { name: "Tacoma Immigration Court", address: "1623 East J Street, Tacoma, WA 98421", courtType: "Detained" },
  { name: "Honolulu Immigration Court", address: "300 Ala Moana Boulevard, Room 8-156, Honolulu, HI 96850", courtType: "Non-detained" },
  { name: "Saipan Immigration Court", address: "Horiguchi Building 2nd Floor Beach Road, Garapan, MP 96950", courtType: "Non-detained" },
  { name: "San Juan Immigration Court", address: "150 Carlos Chardon Avenue, Suite 360, San Juan, PR 00918", courtType: "Non-detained" },
  { name: "Guaynabo Immigration Court", address: "Metro Office Park 7, Calle 1 Suite 102, Guaynabo, PR 00968", courtType: "Non-detained" },
  { name: "Las Cruces Immigration Court", address: "505 South Main Street, Suite 460, Las Cruces, NM 88001", courtType: "Non-detained" },
  { name: "Otero Immigration Court", address: "26 McGregor Range Road, Chaparral, NM 88081", courtType: "Detained" },
  { name: "Cibola Immigration Court", address: "2000 Cibola Loop, Milan, NM 87021", courtType: "Detained" },
  { name: "Boise Immigration Court", address: "1109 Main Street, Suite 300, Boise, ID 83702", courtType: "Non-detained" },
  { name: "Hyattsville-Annapolis Immigration Court", address: "6525 Belcrest Road, Suite 200, Hyattsville, MD 20782", courtType: "Non-detained" },
  { name: "Concord Immigration Court", address: "275 Chestnut Street, Suite 1700, Manchester, NH 03101", courtType: "Non-detained" },
  { name: "Louisville Immigration Court", address: "601 West Broadway, Suite 320, Louisville, KY 40202", courtType: "Non-detained" },
  { name: "Memphis Detained Immigration Court", address: "167 North Main Street, Suite 1100, Memphis, TN 38103", courtType: "Detained" },
  { name: "Nashville Immigration Court", address: "1255 Lynnfield Road, Suite 168, Memphis, TN 38119", courtType: "Non-detained" },
  { name: "Fishkill Immigration Court", address: "750 Berme Road, Napanoch, NY 12458", courtType: "Detained" },
  { name: "Lasalle Immigration Court", address: "830 Pine Hill Road, Jena, LA 71342", courtType: "Detained" },
  { name: "San Francisco - Sansome Immigration Court", address: "630 Sansome Street, Room 1010, San Francisco, CA 94111", courtType: "Non-detained" },
  { name: "San Antonio Annex Immigration Court", address: "8940 Fourwinds Drive, Suite 200, San Antonio, TX 78239", courtType: "Non-detained" },
  { name: "Houston Annex Immigration Court", address: "17171 Pine Forest Lane, Houston, TX 77032", courtType: "Non-detained" },
];
